version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=adapty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    volumes:
      - .:/adapty
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']

volumes:
  postgres_data:
