# Generated by Django 5.0.6 on 2024-05-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('profile_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'MALE'), ('f', 'FEMALE'), ('o', 'OTHER')], max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(primary_key=True, serialize=False)),
                ('app_version', models.CharField(max_length=16)),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('macOS', 'macOS'), ('iPadOS', 'iPadOS'), ('visionOS', 'visionOS'), ('Android', 'Android')], max_length=16)),
                ('timezone', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='adapty_app.user')),
            ],
        ),
    ]
